set(GLFW_BUILD_DOCS OFF CACHE BOOL "" FORCE)
set(GLFW_BUILD_TESTS OFF CACHE BOOL "" FORCE)
set(GLFW_BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
add_subdirectory(${DEPENDS_DIR}/glfw ${CMAKE_BINARY_DIR}/depends/glfw)
target_link_libraries(viewer glfw)
